# -*- coding: utf-8 -*-
"""Aula6-Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aZARsO_vS51ELav8-MImDN5Q9V1ILm0k
"""

#AULA 6:

# n=[2,3,6,89,45]
# print(n)#imprime todos os indices
# index_one = n[4]#trás apenas o indice solicitado
# print(index_one)

# n=[2,3,6,89,45]
# add=n.append(10)#adiciona um item
# add=n.append(5)
# # remove=n.pop()
# # add2=n.pop()#exclui o item
# print(n)

# n=[2,3,6,89,45]
# remove2=n.remove(89) #REMOVE O VALOR
# print(n)
# #del n[0]#REMOVE O ESPAÇO(INDICE)
# print(n)


# n=[2,3,6,89,45]
# comprimento=len(n)
# print(comprimento)

# lista2=[2,6,5,'a','letra',True,3.5]
# for n in lista2:
#    print(n)

# print(lista2)

#------------------------------------------------------------------------------------------------------------

# EXERCÍCIOS :

#**Exercício 1:** Crie uma lista chamada `numeros` que contenha os números inteiros de 1 a 5 e imprima-a na tela.

# numeros=[1,2,3,4,5]
# print(numeros)

#Exercício 2: Acesse e imprima o terceiro elemento da lista numeros.

# numbers=[1,2,3,4,5]
# print('A lista é composta pelos seguintes elementos: \n',numbers)
# index_one = numbers[3]
# print('Sendo que o terceiro elemento da lista é o : ',index_one)

#Exercício 3: Adicione o número 6 à lista numeros e imprima a lista atualizada.
# numbers=[1,2,3,4,5]
# print('Inicialmente a lista é composta pelos seguintes elementos: \n',numbers)
# add=numbers.append(6)
# print('Adicionando o número 6 a lista teremos:\n ',numbers)

#Exercício 4: Remova o número 3 da lista numeros e imprima a lista resultante.
# numbers=[1,2,3,4,5]
# print('Inicialmente a lista é composta pelos seguintes elementos: \n',numbers)
# remove=numbers.remove(3)
# print('Removendo o número 3 a lista teremos:\n ',numbers)

#Exercício 5: Crie uma lista chamada frutas contendo três nomes de frutas diferentes. Em seguida, concatene essa lista com a lista numeros e imprima o resultado.
# frutas=['maça','pera','uva']
# numbers=[1,2,3,4,5]
# print('Inicialmente a lista "números" é composta pelos seguintes elementos: \n',numbers)
# print('E a lista "frutas" é composta pelos seguintes elementos: \n',frutas)
# lista_completa= [numbers,frutas]
# print('Ao juntarmos as duas listas teremos:\n',lista_completa)

#Exercício 6: Use um loop for para percorrer e imprimir todos os elementos da lista frutas.

# frutas=['maça','pera','uva']
# print('A lista "frutas" é composta pelos seguintes elementos: \n',frutas)
# print('---------------------------------------------------------------------------------\n')
# print('Ao percorrer e imprimir os elementos da lista frutas teremos:\n')
# for n in frutas:
#   print(n)

#Exercício 7: Verifique se o número 5 está presente na lista numeros e imprima uma mensagem informando se ele está na lista ou não.
# numbers=[1,2,3,4,5]
# print('Inicialmente a lista é composta pelos seguintes elementos: \n',numbers)
# add=numbers.append(6)
# print('Adicionando o número 6 a lista teremos:\n ',numbers)
# if 5 in numbers:
#   print('O número 5 está na lista')
# else:
#   print('O número 5 não está na lista')

